### ISSUE TITLE
[Bug] Counter doesn't get past 2

### ISSUE THREAD

**Issue by nodgear** [onepiecehung/discord.js-temporary-channel#5]
The function counter never goes past #2, Here's a screenshot showing multiple channels being created https://i.wisp.run/f/8vy8VV.png

**Comment by onepiecehung** [comment]
have you try this without Redis: https://github.com/onepiecehung/discord.js-temporary-channel/blob/master/index.ts

**Comment by onepiecehung** [comment]
hmm... I still don't understand this bug very well, can you explain more?

**Comment by onepiecehung** [comment]
Update to v4 fixed

**Comment by nodgear** [comment]
Oh my, i never got notification from your replies on this issue (got one for closing tho)
